language: scala
sudo: required
dist: trusty

scala:
  - 2.11.0
  - 2.12.1

jdk:
  - oraclejdk8
  - openjdk8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake golang
  - export GOPATH=/tmp
  - export PATH=$GOPATH/bin:$PATH

install:
  - go get -u github.com/yunify/snips

script:
  - make help
  - make update
  - make generate
  - make unit
  - make release
  - make clean

